config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  # get 'posts/index'

  resources 'posts' do
    resources 'comments'
  end

  namespace :api do
    namespace :v1 do
      resources :regions, only: %i[index show], defaults: { format: :json } do
        resources :provinces, only: :index, defaults: { format: :json }
      end

      resources :provinces, only: %i[index show], defaults: { format: :json } do
        resources :cities, only: :index, defaults: { format: :json }
      end

      resources :cities, only: %i[index show], defaults: { format: :json } do
        resources :barangays, only: :index, defaults: { format: :json }
      end

      resources :barangays, only: %i[index show], defaults: { format: :json }
    end
  end
end

app/models/address.rb
module Address
  def self.table_name_prefix
    "address_"
  end
end

app/models/address/barangay.rb
class Address::Barangay < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  belongs_to :city
end

app/models/address/city.rb
class Address::City < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  belongs_to :province
  has_many :barangay
end

app/models/address/province.rb
class Address::Province < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  belongs_to :region
  has_many :cities
end

app/models/address/region.rb
class Address::Region < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  has_many :provinces
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
end

app/controllers/api/v1/barangays_controller.rb
class Api::V1::BarangaysController < ApplicationController

  def index
    city = Address::City.find_by_id(params[:city_id])
    barangays = if city
                  city.barangay
                else
                  Address::Barangay.all? { ||  }
                end
    render json: barangays
  end

  def show
    barangay = Address::Barangay.find(params[:id])
    render json: barangay
  end
end

app/controllers/api/v1/cities_controller.rb
class Api::V1::CitiesController < ApplicationController

  def index
    province = Address::Province.find_by_id(params[:province_id])
    cities = if province
               province.cities
             else
               Address::City.all
             end

    render json: cities
  end

  def show
    city = Address::City.find(params[:id])
    render json: city
  end
end

app/controllers/api/v1/provinces_controller.rb
class Api::V1::ProvincesController < ApplicationController
  def index
    region = Address::Region.find_by_id(params[:region_id])
    provinces = if region
                  region.provinces
                else
                  Address::Province.all
                end

    render json: provinces
  end

  def show
    province = Address::Province.find_by_id(params[:id])
    render json: province
  end
end

app/controllers/api/v1/regions_controller.rb
class Api::V1::RegionsController < ApplicationController
  def index
    regions = Address::Region.all
    render json: regions
  end

  def show
    region = Address::Region.find(params[:id])
    render json: region
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  def index
    @comments = @post.comments.all
  end
  def show;end

  private
  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = 'Post Created Successfully!'
      redirect_to root_path
    end
  end

  def edit;end

  def update
    if @post.update(post_params)
      flash[:notice] = "Updated Successfully"
      redirect_to root_path
    end
  end

  def destroy
    if @post.destroy
      redirect_to root_path
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/index.html.erb
<%= link_to 'New Comment', new_post_comment_path, class: 'btn btn-primary' %>
<table class="table">
  <thead>
  <tr>
    <th scope="col">Content</th>
  </tr>
  </thead>
  <tbody>
  <% @comments.each do |comment| %>
    <tr>
      <td><%= comment.content %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
</head>

<body>
<%= render 'layouts/shared/header' %>
<%= yield %>
</body>
</html>

app/views/layouts/shared/_header.html.erb
<!-- app/views/layouts/_header.html.erb -->
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <%= link_to 'KodaCamp', root_path, class: 'text-decoration-none' %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <%= link_to 'New Post', new_post_path, class: "nav-link active" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/posts/edit.html.erb
<div class="container mt-5">
  <h2 class="mb-4">Update Post</h2>

  <%= form_with model: @post, url: posts_path, method: :post do |form| %>
    <div>
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
    <div>
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>
    <%= form.submit %>
  <% end %>
</div>

app/views/posts/index.html.erb
<table class="table">
  <thead>
  <tr>
    <th scope="col">Title</th>
    <th scope="col">Content</th>
    <th scope="col">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.content %></td>
      <td><%= link_to 'Edit', edit_post_path(post.id), class: 'btn btn-primary' %></td>
      <td><%= link_to 'Comments', post_comments_path(post.id), class: 'btn btn-danger' %></td>
      <td><%= button_to 'Delete', post_path(post.id), method: :delete, class: 'btn btn-danger' %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<div class="container mt-5">
  <h2 class="mb-4">Create a New Post</h2>

  <%= form_with model: @post, url: posts_path, method: :post do |form| %>
    <div>
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
    <div>
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>
    <%= form.submit %>
  <% end %>
</div>